@startuml
title 基于GitHub的实验管理平台-用例图
actor 老师
actor 学生
package 用户用例集 {
老师 --up-> (登录、登出)
老师 --up-> (查看信息)
老师 --up-> (修改信息)
老师 --up-> (修改密码)
学生 --up-> (登录、登出)
学生 --up-> (查看信息)
学生 --up-> (修改信息)
学生 --up-> (修改密码)
}
package 业务用例集 {
老师 ---> (评定成绩)
老师 ---> (查看成绩)
学生 ---> (学生列表)
老师 ---> (学生列表)
学生 ---> (查看成绩)
学生 ---> (课程列表)
老师 ---> (课程列表)
老师 ---> (老师列表)
}

@enduml